-- thinkering DB snapshot, schema v5. Generated by pnpm snapshot.
PRAGMA foreign_keys=OFF;
CREATE TABLE "__drizzle_migrations" (
				id SERIAL PRIMARY KEY,
				hash text NOT NULL,
				created_at numeric
			);
CREATE TABLE `activities` (
	`id` text PRIMARY KEY NOT NULL,
	`interest_id` text NOT NULL,
	`goal_id` text,
	`section` text NOT NULL,
	`tier` text NOT NULL,
	`library_item_id` text NOT NULL,
	`title` text NOT NULL,
	`est_minutes` integer NOT NULL,
	`doc` text,
	`status` text DEFAULT 'planned' NOT NULL,
	`current_page` integer DEFAULT 0 NOT NULL,
	`planned_for` text NOT NULL,
	`started_at` integer,
	`completed_at` integer,
	`rating` text,
	`rating_text` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer, `topic` text, `focus` text, `resource_id` text,
	FOREIGN KEY (`interest_id`) REFERENCES `interests`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`goal_id`) REFERENCES `goals`(`id`) ON UPDATE no action ON DELETE no action
);
CREATE TABLE `analytics_buffer` (
	`id` text PRIMARY KEY NOT NULL,
	`event` text NOT NULL,
	`properties` text NOT NULL,
	`created_at` integer NOT NULL
);
CREATE TABLE `contexts` (
	`id` text PRIMARY KEY NOT NULL,
	`interest_id` text NOT NULL,
	`kind` text NOT NULL,
	`label` text NOT NULL,
	`notes` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	FOREIGN KEY (`interest_id`) REFERENCES `interests`(`id`) ON UPDATE no action ON DELETE no action
);
CREATE TABLE `gen_cache` (
	`id` text PRIMARY KEY NOT NULL,
	`kind` text NOT NULL,
	`scope_key` text NOT NULL,
	`payload` text NOT NULL,
	`created_at` integer NOT NULL,
	`expires_at` integer
);
CREATE TABLE `goals` (
	`id` text PRIMARY KEY NOT NULL,
	`interest_id` text NOT NULL,
	`title` text NOT NULL,
	`description` text NOT NULL,
	`concepts` text NOT NULL,
	`status` text DEFAULT 'not_started' NOT NULL,
	`sort_order` real NOT NULL,
	`source` text NOT NULL,
	`introduced_at` integer,
	`strengthened_at` integer,
	`applied_at` integer,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	FOREIGN KEY (`interest_id`) REFERENCES `interests`(`id`) ON UPDATE no action ON DELETE no action
);
CREATE TABLE `interests` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`want_to_learn` text NOT NULL,
	`why_choice` text NOT NULL,
	`why_text` text,
	`experience_choice` text NOT NULL,
	`experience_text` text,
	`frequency` text NOT NULL,
	`session_minutes` integer NOT NULL,
	`approach_notes` text DEFAULT '' NOT NULL,
	`status` text NOT NULL,
	`sort_order` real NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer
, `success_outcomes` text);
CREATE TABLE `library_prefs` (
	`id` text PRIMARY KEY NOT NULL,
	`interest_id` text NOT NULL,
	`section` text NOT NULL,
	`library_item_id` text NOT NULL,
	`active` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	FOREIGN KEY (`interest_id`) REFERENCES `interests`(`id`) ON UPDATE no action ON DELETE no action
);
CREATE TABLE `llm_calls` (
	`id` text PRIMARY KEY NOT NULL,
	`kind` text NOT NULL,
	`model` text NOT NULL,
	`interest_id` text,
	`activity_id` text,
	`request` text NOT NULL,
	`response` text,
	`input_tokens` integer,
	`output_tokens` integer,
	`latency_ms` integer,
	`status` text NOT NULL,
	`error` text,
	`created_at` integer NOT NULL
);
CREATE TABLE `reflections` (
	`id` text PRIMARY KEY NOT NULL,
	`interest_id` text NOT NULL,
	`feeling_text` text NOT NULL,
	`changes` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	FOREIGN KEY (`interest_id`) REFERENCES `interests`(`id`) ON UPDATE no action ON DELETE no action
);
CREATE TABLE `resources` (
	`id` text PRIMARY KEY NOT NULL,
	`interest_id` text NOT NULL,
	`url` text NOT NULL,
	`title` text NOT NULL,
	`description` text DEFAULT '' NOT NULL,
	`how_to_use` text,
	`summary` text,
	`source` text NOT NULL,
	`goal_ids` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	FOREIGN KEY (`interest_id`) REFERENCES `interests`(`id`) ON UPDATE no action ON DELETE no action
);
CREATE TABLE `responses` (
	`id` text PRIMARY KEY NOT NULL,
	`activity_id` text NOT NULL,
	`page_id` text NOT NULL,
	`block_id` text NOT NULL,
	`payload` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	FOREIGN KEY (`activity_id`) REFERENCES `activities`(`id`) ON UPDATE no action ON DELETE no action
);
CREATE TABLE `routine_notes` (
	`id` text PRIMARY KEY NOT NULL,
	`interest_id` text,
	`note` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	FOREIGN KEY (`interest_id`) REFERENCES `interests`(`id`) ON UPDATE no action ON DELETE no action
);
CREATE TABLE `settings` (
	`key` text PRIMARY KEY NOT NULL,
	`value` text NOT NULL
);
CREATE TABLE `topics` (
	`id` text PRIMARY KEY NOT NULL,
	`interest_id` text NOT NULL,
	`label` text NOT NULL,
	`origin` text NOT NULL,
	`selected` integer NOT NULL,
	`sort_order` real NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	FOREIGN KEY (`interest_id`) REFERENCES `interests`(`id`) ON UPDATE no action ON DELETE no action
);
CREATE INDEX `activities_history_idx` ON `activities` (`interest_id`,`completed_at`);
CREATE INDEX `activities_planned_idx` ON `activities` (`interest_id`,`planned_for`);
CREATE INDEX `contexts_interest_idx` ON `contexts` (`interest_id`);
CREATE INDEX `gen_cache_scope_idx` ON `gen_cache` (`kind`,`scope_key`);
CREATE INDEX `goals_interest_idx` ON `goals` (`interest_id`);
CREATE INDEX `library_prefs_interest_idx` ON `library_prefs` (`interest_id`);
CREATE INDEX `reflections_interest_idx` ON `reflections` (`interest_id`);
CREATE INDEX `resources_interest_idx` ON `resources` (`interest_id`);
CREATE INDEX `responses_activity_idx` ON `responses` (`activity_id`);
CREATE INDEX `topics_interest_idx` ON `topics` (`interest_id`);
INSERT INTO "__drizzle_migrations" ("id", "hash", "created_at") VALUES (NULL, 'fa6d288ce83cceea993fd163d7615dd01cd12ed2aa4e853f3bbc235b7b0b338c', 1789426907118);
INSERT INTO "__drizzle_migrations" ("id", "hash", "created_at") VALUES (NULL, '48b85dcd1bd1029cfc98e811a10bb7224a9615825b23d61f07859875efcb7cfd', 1789451368506);
INSERT INTO "__drizzle_migrations" ("id", "hash", "created_at") VALUES (NULL, '2c215acde1fcbd716bbc95ee408c058fc34277bdc5c5deb7470ce233a9e8d174', 1789759292459);
INSERT INTO "__drizzle_migrations" ("id", "hash", "created_at") VALUES (NULL, '755887e89462ce2ca5c9ca9294edbb5902f4d1e35ffe1007da3aee131f524edc', 1789770189169);
INSERT INTO "__drizzle_migrations" ("id", "hash", "created_at") VALUES (NULL, '8a6f38cf6edc29628e5c4c7584f2f7aae3dedeb9316e8e8798d366fd52dde97f', 1790857043926);
INSERT INTO "activities" ("id", "interest_id", "goal_id", "section", "tier", "library_item_id", "title", "est_minutes", "doc", "status", "current_page", "planned_for", "started_at", "completed_at", "rating", "rating_text", "created_at", "updated_at", "deleted_at", "topic", "focus", "resource_id") VALUES ('a-sample', 'i-sample', 'g-sample', 'next', 'introduce', 'plain-explainer', 'Tokens, not words', 5, NULL, 'completed', 0, '2026-09-14', 1757900000000, 1757900000000, 'up', NULL, 1757900000000, 1757900000000, NULL, NULL, NULL, NULL);
INSERT INTO "analytics_buffer" ("id", "event", "properties", "created_at") VALUES ('ab-sample', 'activity_completed', '{"section":"next"}', 1757900000000);
INSERT INTO "contexts" ("id", "interest_id", "kind", "label", "notes", "created_at", "updated_at", "deleted_at") VALUES ('ctx-sample', 'i-sample', 'project', 'Support-bot prototype', NULL, 1757900000000, 1757900000000, NULL);
INSERT INTO "gen_cache" ("id", "kind", "scope_key", "payload", "created_at", "expires_at") VALUES ('gc-sample', 'daily_plan', 'i-sample:2026-09-14', '{"cards":[]}', 1757900000000, 1757986400000);
INSERT INTO "goals" ("id", "interest_id", "title", "description", "concepts", "status", "sort_order", "source", "introduced_at", "strengthened_at", "applied_at", "created_at", "updated_at", "deleted_at") VALUES ('g-sample', 'i-sample', 'Explain what a token is', 'What tokens are and why they matter for cost and context.', '[{"id":"c-tokens","label":"Tokenization","kind":"concept"}]', 'introduced', 1, 'intake', 1757900000000, NULL, NULL, 1757900000000, 1757900000000, NULL);
INSERT INTO "interests" ("id", "name", "want_to_learn", "why_choice", "why_text", "experience_choice", "experience_text", "frequency", "session_minutes", "approach_notes", "status", "sort_order", "created_at", "updated_at", "deleted_at", "success_outcomes") VALUES ('i-sample', 'Understanding LLMs', 'Understand LLMs and AI', 'career', NULL, 'explored', NULL, 'daily', 10, 'Worked examples first; fade scaffolding with experience.', 'focus', 1, 1757900000000, 1757900000000, NULL, NULL);
INSERT INTO "library_prefs" ("id", "interest_id", "section", "library_item_id", "active", "updated_at", "deleted_at") VALUES ('lp-sample', 'i-sample', 'next', 'mini-case', 0, 1757900000000, NULL);
INSERT INTO "llm_calls" ("id", "kind", "model", "interest_id", "activity_id", "request", "response", "input_tokens", "output_tokens", "latency_ms", "status", "error", "created_at") VALUES ('llm-sample', 'today.plan', 'claude-haiku-4-5-20251001', 'i-sample', NULL, '{"system":"redacted-sample","messages":[]}', '{"cards":[]}', 1200, 180, 900, 'ok', NULL, 1757900000000);
INSERT INTO "reflections" ("id", "interest_id", "feeling_text", "changes", "created_at", "updated_at", "deleted_at") VALUES ('ref-sample', 'i-sample', 'Going well; want more hands-on work.', '{"added":["Explain what a token is"],"removed":[],"revised":[],"reordered":true}', 1757900000000, 1757900000000, NULL);
INSERT INTO "resources" ("id", "interest_id", "url", "title", "description", "how_to_use", "summary", "source", "goal_ids", "created_at", "updated_at", "deleted_at") VALUES ('res-sample', 'i-sample', 'https://example.com/tokenizers', 'How tokenizers work', 'A visual walkthrough.', NULL, NULL, 'suggested', '["g-sample"]', 1757900000000, 1757900000000, NULL);
INSERT INTO "responses" ("id", "activity_id", "page_id", "block_id", "payload", "created_at", "updated_at", "deleted_at") VALUES ('r-sample', 'a-sample', 'p1', 'q1', '{"selectedId":"b"}', 1757900000000, 1757900000000, NULL);
INSERT INTO "routine_notes" ("id", "interest_id", "note", "created_at", "updated_at", "deleted_at") VALUES ('rn-sample', NULL, 'Prefer shorter reading passages.', 1757900000000, 1757900000000, NULL);
INSERT INTO "settings" ("key", "value") VALUES ('posthog_opt_in', 'false');
INSERT INTO "topics" ("id", "interest_id", "label", "origin", "selected", "sort_order", "created_at", "updated_at", "deleted_at") VALUES ('t-sample', 'i-sample', 'Tokenization', 'foundational', 1, 1, 1757900000000, 1757900000000, NULL);
