/**
 * Dumps `fixtures/db/v<N>.sql` — the historical-snapshot convention from
 * docs/10-testing.md Tier 2. Run this when a migration ships: it builds a fresh
 * DB at head, seeds one plausible row per table, and writes a full SQL dump
 * (schema + rows + drizzle migration bookkeeping). The migration-chain test
 * replays every committed snapshot forward to head and asserts rows survive.
 */
import { mkdirSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import Database from 'better-sqlite3'
import { drizzle } from 'drizzle-orm/better-sqlite3'
import { migrate } from 'drizzle-orm/better-sqlite3/migrator'
import * as schema from '../src/schema'
import type { Database as RepoDatabase } from '../src/database'
import { seedSampleRows } from '../test/sample-rows'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

const sqlite = new Database(':memory:')
const db = drizzle(sqlite, { schema })
migrate(db, { migrationsFolder: join(root, 'migrations') })
seedSampleRows(db as unknown as RepoDatabase)

const version = readdirSync(join(root, 'migrations')).filter((f) => f.endsWith('.sql')).length

function sqlLiteral(value: unknown): string {
  if (value === null || value === undefined) return 'NULL'
  if (typeof value === 'number' || typeof value === 'bigint') return String(value)
  if (value instanceof Buffer) return `X'${value.toString('hex')}'`
  return `'${String(value).replace(/'/g, "''")}'`
}

const lines: string[] = [
  '-- thinkering DB snapshot, schema v' + version + '. Generated by pnpm snapshot.',
  'PRAGMA foreign_keys=OFF;',
]

const objects = sqlite
  .prepare(
    "SELECT name, sql FROM sqlite_master WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' ORDER BY CASE type WHEN 'table' THEN 0 ELSE 1 END, name",
  )
  .all() as { name: string; sql: string }[]

for (const obj of objects) lines.push(obj.sql + ';')

const tables = sqlite
  .prepare(
    "SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' ORDER BY name",
  )
  .all() as { name: string }[]

for (const { name } of tables) {
  const rows = sqlite.prepare(`SELECT * FROM "${name}"`).all() as Record<string, unknown>[]
  for (const row of rows) {
    const cols = Object.keys(row)
    lines.push(
      `INSERT INTO "${name}" (${cols.map((c) => `"${c}"`).join(', ')}) VALUES (${cols
        .map((c) => sqlLiteral(row[c]))
        .join(', ')});`,
    )
  }
}

mkdirSync(join(root, 'fixtures/db'), { recursive: true })
const out = join(root, `fixtures/db/v${version}.sql`)
writeFileSync(out, lines.join('\n') + '\n')
console.log(`wrote ${out} (${lines.length} statements)`)
